language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 8.0
  - 8.1
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit

after_script:
  - sh .travis.coverage.sh

matrix:
  allow_failures:
    - php: hhvm
