name: Run CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.3']
        dependencies: ['normal', 'authoritative']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        if: matrix.dependencies == 'normal'
        run: composer install --prefer-dist
        env:
          COMPOSER_ROOT_VERSION: dev-master

      - name: Install dependencies
        if: matrix.dependencies == 'authoritative'
        run: composer install --prefer-dist --classmap-authoritative
        env:
          COMPOSER_ROOT_VERSION: dev-master

      - name: Run Phpunit
        run: php -dzend.assertions=1 ./vendor/bin/phpunit